spring:
  application:
    name: cloud-stream-kafka-functions
  cloud:
    stream:
      function:
        definition: producer;processor;consumer
      bindings:
        producer-out-0:
          destination: original-messages
        processor-in-0:
          destination: original-messages
          group: ${spring.application.name}-processor
        processor-out-0:
          destination: modified-messages
        consumer-in-0:
          destination: modified-messages
          group: ${spring.application.name}-consumer
      kafka:
        binder:
          brokers: localhost:9092
server:
  port: 7000