spring:
  application:
    name: feign-client-sleuth
  sleuth:
    baggage:
      remote-fields: my-trace-id
      correlation-fields: my-trace-id
      tag-fields: my-trace-id
  zipkin:
    base-url: http://localhost:9411
server:
  port: 7000
  servlet:
    context-path: /users
remote-server-url: http://localhost:8000/users/

